Demo/Models/DiscountModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Demo.Models
{
    public class DiscountModel
    {
        [Required]
        [Range(0.1, double.MaxValue, ErrorMessage ="Price must be greater than zero")]
        [DisplayFormat(DataFormatString = "{0:n2}")]
        public decimal ListPrice { get; set; }
        [Required]
        [Range(0.1, double.MaxValue, ErrorMessage = "Discount must be greater than zero")]
        [DisplayFormat(DataFormatString = "{0:n1}")]
        public int Discount { get; set; }
       
        [DisplayFormat(DataFormatString = "{0:n2}")]
        public decimal LessDiscount { get; set; }
       
        public decimal AfterDiscount { get; set; }
      
        public decimal PlusFreight { get; set; }
      
        public decimal Net { get; set; }
        public string WeightId { get; set; }
        public List<SelectListItem> WeightRanges { get; set; }




    }
}

Demo/Models/ErrorViewModel.cs
using System;

namespace Demo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Demo/Models/WeightRanges.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Demo.Models
{
    public class WeightRanges
    {
        public List<SelectListItem> WeightList { get; } = new List<SelectListItem>
        {
            new SelectListItem { Value = "1", Text = "> 0 <=1 kg " },
            new SelectListItem { Value = "2", Text = "> 1 <= 2 kg " },
            new SelectListItem { Value = "3", Text = "> 2 <=5 kg"  },
            new SelectListItem { Value = "4", Text = "> 5 <= 10 kg"  },
          
        };
    }
}

Demo/Controllers/DemoController.cs
using Demo.Interfaces;
using Demo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;

using System.Threading.Tasks;
//using System.Web.Mvc;

namespace Demo.Controllers
{
    
    public class DemoController : Controller
    {
        private readonly IDemoRepository _demoRepository;
        WeightRanges weightRanges = new WeightRanges();

        public DemoController(IDemoRepository demoRepository)
        {
            _demoRepository = demoRepository;
            LoadWeightRanges();
        }
        public void LoadWeightRanges()
        {  

            weightRanges.WeightList.Insert(0, new SelectListItem()
            {
                Text = "----Select----",
                Value = string.Empty
            });
        }

        public IActionResult Index()
        {    
            DiscountModel model = new DiscountModel();
            model.WeightRanges = weightRanges.WeightList.ToList();

            return View(model);
        }
        public IActionResult View2()
        {
            DiscountModel model = new DiscountModel();
            model.WeightRanges = weightRanges.WeightList.ToList();

            return View(model);
        }
        public IActionResult View1()
        {
            DiscountModel model = new DiscountModel();
            model.WeightRanges = weightRanges.WeightList.ToList();

            return View(model);
        }
        [HttpPost]
        public JsonResult View2(string listprice, string discount,string weightId)
        {
            decimal _listprice = Decimal.Parse(listprice);
            decimal _discount = Decimal.Parse(discount);


            decimal lessDiscount = _demoRepository.Discount(_listprice, _discount);
            decimal afterDiscount = _listprice - _discount;

            decimal freight = _demoRepository.Freight(weightId);

            DiscountModel model = new DiscountModel();

            model.LessDiscount = _discount;
            model.AfterDiscount = afterDiscount;
            model.PlusFreight = freight;
            model.Net = afterDiscount + freight;


            return Json(model, new { Success = true });
        }

        [HttpPost]
        public IActionResult Index(DiscountModel model)
        {
            decimal discount = _demoRepository.Discount(model.ListPrice, model.Discount);
            decimal afterDiscount = model.ListPrice - discount;

            decimal freight = _demoRepository.Freight(model.WeightId);

            model.LessDiscount = discount;
            model.AfterDiscount = afterDiscount;
            model.PlusFreight = freight;
            model.Net = afterDiscount + freight;

            model.WeightRanges = weightRanges.WeightList.ToList();

            ViewData["result"] = model;

            return View(model);
        }

    }
}

Demo/Controllers/HomeController.cs
using Demo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Demo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Demo/Views/Demo/Index.cshtml
@model Demo.Models.DiscountModel;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var result = (Demo.Models.DiscountModel)ViewData["result"];

}



<form asp-action="Index" method="post">
    <div asp-validation-summary="All"></div>
    <div class="container" style="width:40%">
        <h1>Discount Calculator</h1>
        <div class="row">
            <div class="col-md-12"><strong>Inputs</strong></div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-6">
                <label asp-for="ListPrice">List Price:</label>
            </div>
            <div class="input-group col-md-6">
                <span class="input-group-text">$</span>
                <input type="text" class="form-control" asp-for="ListPrice" asp-format="{0:N2}"/>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <label asp-for="Discount">Discount:</label>
            </div>
            <div class="input-group col-md-6">
                <input type="text" class="form-control" asp-for="Discount" asp-format="{0:N1}" />
                <span class="input-group-text">%</span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <label asp-for="WeightId">Weight:</label>
            </div>
            <div class="input-group col-md-6">



                <select asp-for="WeightId"
                        class="form-control"
                        asp-items="@(new SelectList(Model.WeightRanges,"Value", "Text"))">
                </select>


            </div>
        </div>

        <br />

        <div class="row">
            <div class="col-md-12"><strong>Output</strong></div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <label asp-for="ListPrice">List Price</label>
            </div>
            <div class="input-group col-md-6">
                <input type="text" class="form-control" asp-for="ListPrice" asp-format="{0:N2}"/>
                <span class="input-group-text">$</span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <label asp-for="LessDiscount">Less Discount</label>
            </div>
            <div class="input-group col-md-6">
                <input type="text" class="form-control" asp-for=@result.LessDiscount asp-format="{0:N2}"/>
                <span class="input-group-text">$</span>
            </div>
        </div>



        <div class="row">
            <div class="col-md-6">
                <label asp-for="AfterDiscount">After Discount</label>
            </div>
            <div class="input-group col-md-6">
                <input type="text" class="form-control" asp-for=@result.AfterDiscount asp-format="{0:N2}"/>
                <span class="input-group-text">$</span>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <label asp-for="PlusFreight">Plus Freight</label>
            </div>
            <div class="input-group col-md-6">
                <input type="text" class="form-control" asp-for=@result.PlusFreight asp-format="{0:N2}"/>
                <span class="input-group-text">$</span>
            </div>
        </div>


        <div class="row">
            <div class="col-md-6">
                <label asp-for="Net">Net</label>
            </div>
            <div class="input-group col-md-6">
                <input type="text" class="form-control" asp-for=@result.Net asp-format="{0:N2}"/>

                <span class="input-group-text">$</span>
            </div>
        </div>

        <br />

        <div class="row d-flex justify-content-center">
            <div class="col-md-4">
                <button type="reset" class="btn btn-outline-primary mr-1">Reset</button>
            </div>
            <div class="col-md-4">
                <button type="submit" class="btn btn-outline-danger">Submit</button>
            </div>

            <div class="col-md-4">
                
                
                <div>
                    <span>$</span>
                    <a asp-controller="Demo" asp-action="View2" class="btn btn-link text-uppercase"
                       style="text-decoration: none; padding:0;">View 2</a>
                    <span>$</span>
                </div>
                
            </div>

        </div>
        
    </div>
</form>

Demo/Views/Demo/UpdateResult.cshtml
@model Demo.Models.DiscountModel;
@{
    ViewData["Title"] = "UpdateResult";
    Layout = "~/Views/Shared/_Layout.cshtml";



}




    <div asp-validation-summary="All"></div>
    <div class="container">
        <h1>Discount Calculator</h1>
        <div class="row">
            <div class="col-4"><strong>Inputs</strong></div>
        </div>
        <br />
        <div class="row">
            <div class="col-2">
                <label asp-for="ListPrice">List Price:</label>
            </div>
            <div class="input-group col-3">
                <span class="input-group-text">$</span>
                <input type="text" class="form-control" asp-for="ListPrice" />
            </div>
        </div>

        <div class="row">
            <div class="col-2">
                <label asp-for="Discount">Discount:</label>
            </div>
            <div class="input-group col-3">
                <input type="text" class="form-control" asp-for="Discount" />
                <span class="input-group-text">%</span>
            </div>
        </div>
        <div class="row">
            <div class="col-2">
                <label asp-for="WeightId">Weight:</label>
            </div>
            <div class="input-group col-3">



                <select asp-for="WeightId"
                        class="form-control"
                        asp-items="@(new SelectList(Model.WeightRanges,"Value", "Text"))">
                </select>


            </div>
        </div>

        <br />

        <div class="row">
            <div class="col-4"><strong>Output</strong></div>
        </div>

        <div class="row">
            <div class="col-2">
                <label asp-for="ListPrice">List Price</label>
            </div>
            <div class="input-group col-3">
                <input type="text" class="form-control" asp-for="ListPrice" />
                <span class="input-group-text">$</span>
            </div>
        </div>
        <div class="row">
            <div class="col-2">
                <label asp-for="LessDiscount">Less Discount</label>
            </div>
            <div class="input-group col-3">
                <input type="text" class="form-control" asp-for=LessDiscount />
                <span class="input-group-text">$</span>
            </div>
        </div>



        <div class="row">
            <div class="col-2">
                <label asp-for="AfterDiscount">After Discount</label>
            </div>
            <div class="input-group col-3">
                <input type="text" class="form-control" asp-for=AfterDiscount />
                <span class="input-group-text">$</span>
            </div>
        </div>

        <div class="row">
            <div class="col-2">
                <label asp-for="PlusFreight">Plus Freight</label>
            </div>
            <div class="input-group col-3">
                <input type="text" class="form-control" asp-for=PlusFreight />
                <span class="input-group-text">$</span>
            </div>
        </div>


        <div class="row">
            <div class="col-2">
                <label asp-for="Net">Net</label>
            </div>
            <div class="input-group col-3">
                <input type="text" class="form-control" asp-for=Net />

                <span class="input-group-text">$</span>
            </div>
        </div>

        <br />

        <div class="row">
            <div class="col-2">
                <button type="button" class="btn btn-outline-primary mr-1">Reset</button>
            </div>
            <div class="col-3">
                <button type="submit" class="btn btn-outline-danger float-right">Submit</button>
            </div>
        </div>

    </div>

Demo/Views/Demo/View1.cshtml
@model Demo.Models.DiscountModel;
@{
    ViewData["Title"] = "View1";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var result = (Demo.Models.DiscountModel)ViewData["result"];

}



<form class="form-inline" asp-action="Index" method="post" >
    <div asp-validation-summary="All"></div>

    <div class="container">
        <table class="table  table-bordered" style="width:50%;">
            <thead>
                <tr>
                    <th colspan="2"><h1>Discount Calculator</h1></th>
                </tr>
                <tr>
                    <th colspan="2"></th>
                </tr>
                <tr>
                    <th colspan="2"><h3>Inputs</h3></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                   
                    <td>

                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Price</span>
                            </div>
                            <span class="input-group-text">$</span>
                            <input type="text" class="form-control" asp-for="ListPrice" />
                        </div>


                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Discount</span>
                            </div>

                            <input type="text" class="form-control" asp-for="Discount" />
                            <span class="input-group-text">%</span>
                        </div>
                    </td>
                </tr>

                <tr>
                    <td>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Weight</span>
                            </div>
                            <div class="input-group">



                                <select asp-for="WeightId"
                                        class="form-control"
                                        asp-items="@(new SelectList(Model.WeightRanges,"Value", "Text"))">
                                </select>


                            </div>
                        </div>
                    </td>
                </tr>
            </tbody>
                
            
        </table>

        
        
        
        <br />
       

        
    

        <br />

        <div class="row">
            <div class="col-4"><strong>Output</strong></div>
        </div>

        <div class="row">
            <div class="col-2">
                <label asp-for="ListPrice">List Price</label>
            </div>
            <div class="input-group col-3">
                <input type="text" class="form-control" asp-for="ListPrice" />
                <span class="input-group-text">$</span>
            </div>
        </div>
        <div class="row">
            <div class="col-2">
                <label asp-for="LessDiscount">Less Discount</label>
            </div>
            <div class="input-group col-3">
                <input type="text" class="form-control" asp-for=@result.LessDiscount />
                <span class="input-group-text">$</span>
            </div>
        </div>



        <div class="row">
            <div class="col-2">
                <label asp-for="AfterDiscount">After Discount</label>
            </div>
            <div class="input-group col-3">
                <input type="text" class="form-control" asp-for=@result.AfterDiscount />
                <span class="input-group-text">$</span>
            </div>
        </div>

        <div class="row">
            <div class="col-2">
                <label asp-for="PlusFreight">Plus Freight</label>
            </div>
            <div class="input-group col-3">
                <input type="text" class="form-control" asp-for=@result.PlusFreight />
                <span class="input-group-text">$</span>
            </div>
        </div>


        <div class="row">
            <div class="col-2">
                <label asp-for="Net">Net</label>
            </div>
            <div class="input-group col-3">
                <input type="text" class="form-control" asp-for=@result.Net />

                <span class="input-group-text">$</span>
            </div>
        </div>

        <br />

        <div class="row d-flex justify-content-center">
            <div class="col-3">
                <button type="reset" class="btn btn-outline-primary mr-1">Reset</button>
            </div>
            <div class="col-3">
                <button type="submit" class="btn btn-outline-danger">Submit</button>
            </div>

            <div class="col-3">

                <a asp-controller="Demo" asp-action="View2">
                    <input type="button" class="btn btn-outline-primary" value="VIEW 2" />
                </a>
            </div>

        </div>

    </div>
</form>

Demo/Views/Demo/View2.cshtml
@model Demo.Models.DiscountModel;
@{
    ViewData["Title"] = "View2";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var result = (Demo.Models.DiscountModel)ViewData["result"];
}

<form asp-action="View2" method="post">
    <div asp-validation-summary="All"></div>
    <div class="container">
        <h1>Discount Calculator</h1>
        <div class="row">
            <div class="col-4"><strong>Inputs</strong></div>
        </div>
        <br />
        <div class="row">
            <div class="col-2">
                <label asp-for="ListPrice">List Price:</label>
            </div>
            <div class="input-group col-3">
                <span class="input-group-text">$</span>
                <input type="text" class="form-control" asp-for="ListPrice" />
            </div>
        </div>

        <div class="row">
            <div class="col-2">
                <label asp-for="Discount">Discount:</label>
            </div>
            <div class="input-group col-3">
                <input type="text" class="form-control" asp-for="Discount" />
                <span class="input-group-text">%</span>
            </div>
        </div>
        <div class="row">
            <div class="col-2">
                <label asp-for="WeightId">Weight:</label>
            </div>
            <div class="input-group col-3">



                <select asp-for="WeightId"
                        class="form-control"
                        asp-items="@(new SelectList(Model.WeightRanges,"Value", "Text"))">
                </select>


            </div>
        </div>

        <br />

        <div class="row">
            <div class="col-4"><strong>Output</strong></div>
        </div>

        <div class="row">
            <div class="col-2">
                <label asp-for="ListPrice">List Price</label>
            </div>
            <div class="input-group col-3">
                <input id="txtPrice" type="text" class="form-control" asp-for="ListPrice" />
                <span class="input-group-text">$</span>
            </div>
        </div>
        <div class="row">
            <div class="col-2">
                <label asp-for="LessDiscount">Less Discount</label>
            </div>
            <div class="input-group col-3">
                <input type="text" class="form-control" asp-for=@result.LessDiscount />
                <span class="input-group-text">$</span>
            </div>
        </div>



        <div class="row">
            <div class="col-2">
                <label asp-for="AfterDiscount">After Discount</label>
            </div>
            <div class="input-group col-3">
                <input type="text" class="form-control" asp-for=@result.AfterDiscount />
                <span class="input-group-text">$</span>
            </div>
        </div>

        <div class="row">
            <div class="col-2">
                <label asp-for="PlusFreight">Plus Freight</label>
            </div>
            <div class="input-group col-3">
                <input type="text" class="form-control" asp-for=@result.PlusFreight />
                <span class="input-group-text">$</span>
            </div>
        </div>


        <div class="row">
            <div class="col-2">
                <label asp-for="Net">Net</label>
            </div>
            <div class="input-group col-3">
                <input type="text" class="form-control" asp-for=@result.Net />

                <span class="input-group-text">$</span>
            </div>
        </div>

        <br />

        <div class="row d-flex justify-content-center">
            <div class="col-3">
                <button type="reset" class="btn btn-outline-primary mr-1">Reset</button>
            </div>
            <div class="col-3">
                <button id="submitButton" type="submit" class="btn btn-outline-danger">Submit</button>
            </div>

           

        </div>

    </div>
</form>

<script type="text/javascript">

    $(document).ready(function () {
        $("#submitButton").click(function () {

          $.ajax({
                type: "POST",
                url: "/Demo/View2",
                dataType: 'json',
                contentType: "application/json",
                data: JSON.stringify({ listprice: ListPrice, discount: Discount, weightId: WeightId}),
                success: function (data) {
                    if (data.Success) {
                        alert(data);
                    }
                    else {
                        window.location.href = '@Url.Action("Demo","Index")';
                    }
                },
                error: function (data) {
                    alert("Something went wrong")
                }
            });

         );




    });


</script>

Demo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Demo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>